[general]
renice = 10
softrealtime = auto
inhibit_screensaver = 1
; Governor durante o jogo. Sem isto o sistema fica em powersave mesmo jogando.
desiredgov = performance
defaultgov = powersave

[custom]
start = @HOME@/.local/bin/gamemode-start.sh
end = @HOME@/.local/bin/gamemode-end.sh
